# Generated by Django 3.2.9 on 2021-11-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservation',
        ),
    ]
