# Generated by Django 3.2.9 on 2021-11-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20211116_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_option',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateField(),
        ),
    ]
